import { Router } from 'express';
import { forumController } from '../controller/forum.controller';
import { authenticate } from '../../../core/middleware/auth';
import { auditLog } from '../../../core/middleware/audit';
const router = Router();
router.get('/categories', (req, res, next) => forumController.getCategories(req, res, next));
router.post('/categories', authenticate as never, auditLog('CREATE_CATEGORY', 'forum') as never, (req, res, next) => forumController.createCategory(req, res, next));
router.get('/posts', (req, res, next) => forumController.getPosts(req, res, next));
router.get('/posts/search', (req, res, next) => forumController.searchPosts(req, res, next));
router.post('/posts', authenticate as never, auditLog('CREATE_POST', 'forum') as never, (req, res, next) => forumController.createPost(req, res, next));
router.get('/posts/:id', (req, res, next) => forumController.getPost(req, res, next));
router.put('/posts/:id', authenticate as never, auditLog('UPDATE_POST', 'forum') as never, (req, res, next) => forumController.updatePost(req, res, next));
router.delete('/posts/:id', authenticate as never, auditLog('DELETE_POST', 'forum') as never, (req, res, next) => forumController.deletePost(req, res, next));
router.post('/posts/:id/replies', authenticate as never, (req, res, next) => forumController.createReply(req, res, next));
router.delete('/posts/:id/replies/:replyId', authenticate as never, (req, res, next) => forumController.deleteReply(req, res, next));
router.post('/posts/:id/pin', authenticate as never, auditLog('PIN_POST', 'forum') as never, (req, res, next) => forumController.pinPost(req, res, next));
router.post('/posts/:id/unpin', authenticate as never, auditLog('UNPIN_POST', 'forum') as never, (req, res, next) => forumController.unpinPost(req, res, next));
router.post('/posts/:id/lock', authenticate as never, auditLog('LOCK_POST', 'forum') as never, (req, res, next) => forumController.lockPost(req, res, next));
router.post('/posts/:id/unlock', authenticate as never, auditLog('UNLOCK_POST', 'forum') as never, (req, res, next) => forumController.unlockPost(req, res, next));
router.post('/posts/:id/move', authenticate as never, auditLog('MOVE_POST', 'forum') as never, (req, res, next) => forumController.movePost(req, res, next));
export { router as forumRouter };