import { Router } from 'express';
import { notificationsController } from '../controller/notifications.controller';
import { authenticate } from '../../../core/middleware/auth';
import { auditLog } from '../../../core/middleware/audit';
const router = Router();
router.get('/', authenticate as never, (req, res, next) => notificationsController.getAll(req, res, next));
router.get('/unread-count', authenticate as never, (req, res, next) => notificationsController.getUnreadCount(req, res, next));
router.post('/mark-all-read', authenticate as never, (req, res, next) => notificationsController.markAllAsRead(req, res, next));
router.delete('/all', authenticate as never, (req, res, next) => notificationsController.deleteAll(req, res, next));
router.post('/', authenticate as never, (req, res, next) => notificationsController.create(req, res, next));
router.post('/bulk', authenticate as never, auditLog('SEND_BULK', 'notification') as never, (req, res, next) => notificationsController.sendBulk(req, res, next));
router.post('/:id/read', authenticate as never, (req, res, next) => notificationsController.markAsRead(req, res, next));
router.delete('/:id', authenticate as never, (req, res, next) => notificationsController.delete(req, res, next));
export { router as notificationsRouter };