import { Router } from 'express';
import { paymentsController } from '../controller/payments.controller';
import { authenticate } from '../../../core/middleware/auth';
import { auditLog } from '../../../core/middleware/audit';
const router = Router();
router.get('/', authenticate as never, (req, res, next) => paymentsController.findAll(req, res, next));
router.get('/my', authenticate as never, (req, res, next) => paymentsController.getMyPayments(req, res, next));
router.get('/revenue', authenticate as never, (req, res, next) => paymentsController.getRevenue(req, res, next));
router.post('/intent', authenticate as never, auditLog('CREATE_PAYMENT', 'payment') as never, (req, res, next) => paymentsController.createPaymentIntent(req, res, next));
router.post('/webhook', (req, res, next) => paymentsController.handleWebhook(req, res, next));
router.get('/:id', authenticate as never, (req, res, next) => paymentsController.findById(req, res, next));
router.post('/:id/refund', authenticate as never, auditLog('REFUND_PAYMENT', 'payment') as never, (req, res, next) => paymentsController.refund(req, res, next));
export { router as paymentsRouter };
