import { Router } from 'express';
import { commentsController } from '../controller/comments.controller';
import { authenticate } from '../../../core/middleware/auth';
import { auditLog } from '../../../core/middleware/audit';
const router = Router();
router.get('/', authenticate as never, (req, res, next) => commentsController.findAll(req, res, next));
router.post('/', authenticate as never, auditLog('CREATE', 'comments') as never, (req, res, next) => commentsController.create(req, res, next));
router.get('/:id', authenticate as never, (req, res, next) => commentsController.findById(req, res, next));
router.put('/:id', authenticate as never, auditLog('UPDATE', 'comments') as never, (req, res, next) => commentsController.update(req, res, next));
router.delete('/:id', authenticate as never, auditLog('DELETE', 'comments') as never, (req, res, next) => commentsController.delete(req, res, next));
export { router as commentsRouter };