import { Router } from 'express';
import { releasesController } from '../controller/releases.controller';
import { authenticate } from '../../../core/middleware/auth';
import { auditLog } from '../../../core/middleware/audit';
const router = Router();
router.get('/', authenticate as never, (req, res, next) => releasesController.findAll(req, res, next));
router.post('/', authenticate as never, auditLog('CREATE', 'releases') as never, (req, res, next) => releasesController.create(req, res, next));
router.get('/:id', authenticate as never, (req, res, next) => releasesController.findById(req, res, next));
router.put('/:id', authenticate as never, auditLog('UPDATE', 'releases') as never, (req, res, next) => releasesController.update(req, res, next));
router.delete('/:id', authenticate as never, auditLog('DELETE', 'releases') as never, (req, res, next) => releasesController.delete(req, res, next));
export { router as releasesRouter };