import { Router } from 'express';
import { chatController } from '../controller/chat.controller';
import { authenticate } from '../../../core/middleware/auth';
import { auditLog } from '../../../core/middleware/audit';
const router = Router();
router.get('/rooms', authenticate as never, (req, res, next) => chatController.getRooms(req, res, next));
router.post('/rooms', authenticate as never, auditLog('CREATE_ROOM', 'chat') as never, (req, res, next) => chatController.createRoom(req, res, next));
router.post('/dm', authenticate as never, (req, res, next) => chatController.createDM(req, res, next));
router.get('/unread', authenticate as never, (req, res, next) => chatController.getUnreadCount(req, res, next));
router.get('/rooms/:id/messages', authenticate as never, (req, res, next) => chatController.getMessages(req, res, next));
router.post('/rooms/:id/messages', authenticate as never, (req, res, next) => chatController.sendMessage(req, res, next));
router.get('/rooms/:id/search', authenticate as never, (req, res, next) => chatController.searchMessages(req, res, next));
router.post('/rooms/:id/read', authenticate as never, (req, res, next) => chatController.markAsRead(req, res, next));
router.post('/rooms/:id/members', authenticate as never, auditLog('ADD_MEMBER', 'chat') as never, (req, res, next) => chatController.addMember(req, res, next));
router.delete('/rooms/:id/members/:userId', authenticate as never, auditLog('REMOVE_MEMBER', 'chat') as never, (req, res, next) => chatController.removeMember(req, res, next));
router.post('/rooms/:id/leave', authenticate as never, (req, res, next) => chatController.leaveRoom(req, res, next));
router.delete('/messages/:messageId', authenticate as never, (req, res, next) => chatController.deleteMessage(req, res, next));
router.put('/messages/:messageId', authenticate as never, (req, res, next) => chatController.editMessage(req, res, next));
export { router as chatRouter };