import { Router } from 'express';
import { blogController } from '../controller/blog.controller';
import { authenticate } from '../../../core/middleware/auth';
import { auditLog } from '../../../core/middleware/audit';
const router = Router();
router.get('/', (req, res, next) => blogController.findAll(req, res, next));
router.get('/search', (req, res, next) => blogController.search(req, res, next));
router.get('/featured', (req, res, next) => blogController.getFeatured(req, res, next));
router.get('/categories', (req, res, next) => blogController.getCategories(req, res, next));
router.post('/categories', authenticate as never, auditLog('CREATE_CATEGORY', 'blog') as never, (req, res, next) => blogController.createCategory(req, res, next));
router.get('/slug/:slug', (req, res, next) => blogController.findBySlug(req, res, next));
router.post('/', authenticate as never, auditLog('CREATE_POST', 'blog') as never, (req, res, next) => blogController.create(req, res, next));
router.get('/:id', (req, res, next) => blogController.findById(req, res, next));
router.put('/:id', authenticate as never, auditLog('UPDATE_POST', 'blog') as never, (req, res, next) => blogController.update(req, res, next));
router.delete('/:id', authenticate as never, auditLog('DELETE_POST', 'blog') as never, (req, res, next) => blogController.delete(req, res, next));
router.post('/:id/publish', authenticate as never, auditLog('PUBLISH_POST', 'blog') as never, (req, res, next) => blogController.publish(req, res, next));
router.post('/:id/unpublish', authenticate as never, auditLog('UNPUBLISH_POST', 'blog') as never, (req, res, next) => blogController.unpublish(req, res, next));
router.post('/:id/featured', authenticate as never, auditLog('TOGGLE_FEATURED', 'blog') as never, (req, res, next) => blogController.toggleFeatured(req, res, next));
export { router as blogRouter };