import { Router } from 'express';
import { apartmentsController } from '../controller/apartments.controller';
import { authenticate } from '../../../core/middleware/auth';
import { auditLog } from '../../../core/middleware/audit';
const router = Router();
router.get('/', authenticate as never, (req, res, next) => apartmentsController.findAll(req, res, next));
router.post('/', authenticate as never, auditLog('CREATE', 'apartments') as never, (req, res, next) => apartmentsController.create(req, res, next));
router.get('/:id', authenticate as never, (req, res, next) => apartmentsController.findById(req, res, next));
router.put('/:id', authenticate as never, auditLog('UPDATE', 'apartments') as never, (req, res, next) => apartmentsController.update(req, res, next));
router.delete('/:id', authenticate as never, auditLog('DELETE', 'apartments') as never, (req, res, next) => apartmentsController.delete(req, res, next));
export { router as apartmentsRouter };